platform :ios, '11.0'
use_frameworks!

target 'Boquila_Example' do
  pod 'Firebase/Analytics'
  pod 'Firebase/RemoteConfig' 

  pod 'Boquila/Firebase', :path => '../'
  pod 'Boquila/Testing', :path => '../'

  target 'Boquila_Tests' do
    inherit! :search_paths    
  end
end
